# Generated by Django 5.1.4 on 2025-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_product_recycling_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='waste_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
